spring:
  jpa:
    properties:
      hibernate.jdbc.batch_size: 30
      hibernate.order_updates: true
      hibernate.order_inserts: true
    open-in-view: false
    hibernate:
      ddl-auto: validate

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            scope: [ email, profile ]
            redirect-uri: ${server.url}/login/oauth2/code/google
        provider:
          google:
            user-name-attribute: email

    jwt:
      expires: 24h
      private: rsa/private.pem
      public: rsa/public.pem

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    ssl.enabled: true

  main:
    banner-mode: off
    problemdetails.enabled: true

server:
  port: 8080
  url: ${BASE_URL:http://localhost:${server.port}}

logging:
  level:
    sql: debug
    web: debug


#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      group-id: my-app-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: '*' # Разрешаем десериализацию из любого пакета